version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: github_scrapper
      POSTGRES_PASSWORD: github_scrapper
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/myapp
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  web:
    command: rails server -b 0.0.0.0
    build: .
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
      DATABASE_URL: db
      POSTGRES_HOST: db
      POSTGRES_USER: github_scrapper
      POSTGRES_PASSWORD: github_scrapper
    volumes:
      - .:/myapp
    depends_on:
      - db
      - webpack
    ports:
      - "3000:3000"
